version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-v1
      - run:
          name: Set up GPG and sbt-pgp
          command: |
            # See https://discuss.circleci.com/t/gpg-keys-as-environment-variables/28641/3
            echo -e "$OSSRH_GPG_KEY" | gpg --import
            mkdir ~/.sbt/gpg
            gpg -a --export-secret-keys >~/.sbt/gpg/secring.asc
            mkdir -p ~/.sbt/1.0/plugins
            echo 'addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.0.0")' >~/.sbt/1.0/plugins/pgp.sbt
      - run:
          name: Write OSSRH credentials
          command: |
            mkdir -p ~/.sbt/1.0
            echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$SONATYPE_USERNAME\", \"$SONATYPE_PASSWORD\")" >>~/.sbt/1.0/sonatype.sbt
            echo "pgpPassphrase := Some(Array[Char]())" >>~/.sbt/1.0/sonatype.sbt
      - run:
          name: Build
          command: |
            sbt clean update package test
      - run:
          name: Clear secret data before caching
          command: |
            rm -fr ~/.sbt/gpg
            rm ~/.sbt/1.0/sonatype.sbt
      - save_cache:
          key: sbt-cache-v1
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - store_test_results:
          path: target/test-reports
      - run:
          name: Publish (master branch only)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sbt publishSigned
            fi
